Resolve primary and secondary hosts on the fly

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -407,8 +407,11 @@ update_instance:
   script:
     - |
       if [[ "${INSTANCE}" == "lhcb.cern.ch" ]]; then
-        dirac-admin-update-instance ${CI_COMMIT_TAG} --retry=2 --hosts=ops/secondaryHosts.txt || echo "Allow failure"
-        dirac-admin-update-instance ${CI_COMMIT_TAG} --retry=2 --hosts=ops/primaryHosts.txt
+        dirac-admin-sysadmin-cli <<< "show hosts" | awk '{print $2}' | grep -E "(\..*){2}" > allHosts.txt
+        grep ".cern.ch" allHosts.txt > primaryHosts.txt
+        grep -v ".cern.ch" allHosts.txt > secondaryHosts.txt
+        dirac-admin-update-instance ${CI_COMMIT_TAG} --retry=2 --hosts=secondaryHosts.txt || echo "Allow failure"
+        dirac-admin-update-instance ${CI_COMMIT_TAG} --retry=2 --hosts=primaryHosts.txt
       else
         dirac-admin-update-instance ${CI_COMMIT_TAG} --retry=2
       fi
