run ci on forks

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -5,7 +5,7 @@ on: [push, pull_request]
 jobs:
   Integration:
     runs-on: ubuntu-latest
-    if: github.event_name != 'push' || github.repository == 'DIRACGrid/DIRAC'
+    # if: github.event_name != 'push' || github.repository == 'DIRACGrid/DIRAC'
     timeout-minutes: 45
 
     env:
@@ -64,44 +64,43 @@ jobs:
     - name: Clean up GitHub actions environment
       run: |
         # Prepare wrapper script
-        echo "#!/usr/bin/env bash" >> run_in_container
-        echo "set -euo pipefail" >> run_in_container
-        echo "IFS=\$'\n\t'" >> run_in_container
-        echo -n "exec docker exec -w /repo " >> run_in_container
+        # echo "#!/usr/bin/env bash" >> run_in_container
+        # echo "set -euo pipefail" >> run_in_container
+        # echo "IFS=\$'\n\t'" >> run_in_container
+        # echo -n "exec docker exec -w /repo " >> run_in_container
         # Set environment variables
-        echo -n "-e HOST_OS=${{ matrix.HOST_OS || env.MATRIX_DEFAULT_HOST_OS }} " >> run_in_container
-        echo -n "-e CI_PROJECT_DIR=/repo " >> run_in_container
-        echo -n "-e CI_COMMIT_REF_NAME=$GITHUB_REF " >> run_in_container
-        echo -n "-e CI_MERGE_REQUEST_TARGET_BRANCH_NAME=$GITHUB_BASE_REF " >> run_in_container
-        echo -n "-e CI_REGISTRY_IMAGE=diracgrid " >> run_in_container
-        echo -n "-e MYSQL_VER=${{ matrix.MYSQL_VER || env.MATRIX_DEFAULT_MYSQL_VER }} " >> run_in_container
-        echo -n "-e ES_VER=${{ matrix.ES_VER || env.MATRIX_DEFAULT_ES_VER }} " >> run_in_container
-        if [[ "${{ matrix.USE_NEWTHREADPOOL || env.MATRIX_DEFAULT_USE_NEWTHREADPOOL }}" != "default" ]]; then echo -n "-e DIRAC_USE_NEWTHREADPOOL=${{ matrix.USE_NEWTHREADPOOL || env.MATRIX_DEFAULT_USE_NEWTHREADPOOL }} " >> run_in_container; fi
-        if [[ "${{ matrix.DIRACOSVER || env.MATRIX_DEFAULT_DIRACOSVER }}" != "default" ]]; then echo -n "-e DIRACOSVER=${{ matrix.DIRACOSVER || env.MATRIX_DEFAULT_DIRACOSVER }} " >> run_in_container; fi
-        echo -n "-e TEST_HTTPS=${{ matrix.TEST_HTTPS || env.MATRIX_DEFAULT_TEST_HTTPS }} " >> run_in_container
-        echo -n "-e SERVER_USE_PYTHON3=${{ matrix.SERVER_USE_PYTHON3 || env.MATRIX_DEFAULT_SERVER_USE_PYTHON3 }} " >> run_in_container
-        if [[ "${{ matrix.SERVER_DIRACOSVER || env.MATRIX_DEFAULT_SERVER_DIRACOSVER }}" != "default" ]]; then echo -n "-e SERVER_DIRACOSVER=${{ matrix.SERVER_DIRACOSVER || env.MATRIX_DEFAULT_SERVER_DIRACOSVER }} " >> run_in_container; fi
-        echo -n "-e CLIENT_USE_PYTHON3=${{ matrix.CLIENT_USE_PYTHON3 || env.MATRIX_DEFAULT_CLIENT_USE_PYTHON3 }} " >> run_in_container
-        if [[ "${{ matrix.CLIENT_DIRACOSVER || env.MATRIX_DEFAULT_CLIENT_DIRACOSVER }}" != "default" ]]; then echo -n "-e CLIENT_DIRACOSVER=${{ matrix.CLIENT_DIRACOSVER || env.MATRIX_DEFAULT_CLIENT_DIRACOSVER }} " >> run_in_container; fi
+        echo -n "export HOST_OS=${{ matrix.HOST_OS || env.MATRIX_DEFAULT_HOST_OS }} " >> run_in_container
+        echo -n "export CI_PROJECT_DIR=/repo " >> run_in_container
+        echo -n "export CI_COMMIT_REF_NAME=$GITHUB_REF " >> run_in_container
+        echo -n "export CI_MERGE_REQUEST_TARGET_BRANCH_NAME=$GITHUB_BASE_REF " >> run_in_container
+        echo -n "export CI_REGISTRY_IMAGE=diracgrid " >> run_in_container
+        echo -n "export MYSQL_VER=${{ matrix.MYSQL_VER || env.MATRIX_DEFAULT_MYSQL_VER }} " >> run_in_container
+        echo -n "export ES_VER=${{ matrix.ES_VER || env.MATRIX_DEFAULT_ES_VER }} " >> run_in_container
+        if [[ "${{ matrix.USE_NEWTHREADPOOL || env.MATRIX_DEFAULT_USE_NEWTHREADPOOL }}" != "default" ]]; then echo -n "export DIRAC_USE_NEWTHREADPOOL=${{ matrix.USE_NEWTHREADPOOL || env.MATRIX_DEFAULT_USE_NEWTHREADPOOL }} " >> run_in_container; fi
+        if [[ "${{ matrix.DIRACOSVER || env.MATRIX_DEFAULT_DIRACOSVER }}" != "default" ]]; then echo -n "export DIRACOSVER=${{ matrix.DIRACOSVER || env.MATRIX_DEFAULT_DIRACOSVER }} " >> run_in_container; fi
+        echo -n "export TEST_HTTPS=${{ matrix.TEST_HTTPS || env.MATRIX_DEFAULT_TEST_HTTPS }} " >> run_in_container
+        echo -n "export SERVER_USE_PYTHON3=${{ matrix.SERVER_USE_PYTHON3 || env.MATRIX_DEFAULT_SERVER_USE_PYTHON3 }} " >> run_in_container
+        if [[ "${{ matrix.SERVER_DIRACOSVER || env.MATRIX_DEFAULT_SERVER_DIRACOSVER }}" != "default" ]]; then echo -n "export SERVER_DIRACOSVER=${{ matrix.SERVER_DIRACOSVER || env.MATRIX_DEFAULT_SERVER_DIRACOSVER }} " >> run_in_container; fi
+        echo -n "export CLIENT_USE_PYTHON3=${{ matrix.CLIENT_USE_PYTHON3 || env.MATRIX_DEFAULT_CLIENT_USE_PYTHON3 }} " >> run_in_container
+        if [[ "${{ matrix.CLIENT_DIRACOSVER || env.MATRIX_DEFAULT_CLIENT_DIRACOSVER }}" != "default" ]]; then echo -n "export CLIENT_DIRACOSVER=${{ matrix.CLIENT_DIRACOSVER || env.MATRIX_DEFAULT_CLIENT_DIRACOSVER }} " >> run_in_container; fi
         # Finish wrapper script
-        echo -n "dirac-testing-host \"\$@\"" >> run_in_container
-        chmod +x run_in_container
+        # echo -n "dirac-testing-host \"\$@\"" >> run_in_container
+        # chmod +x run_in_container
         # Show the run in container script
         echo "Run in container script is"
         cat run_in_container
     - name: Prepare environment
       run: |
-        docker run --name dirac-testing-host -v $PWD:/repo/DIRAC --detach --privileged -v /var/run/docker.sock:/var/run/docker.sock --rm ghcr.io/diracgrid/management/docker-compose-dirac:latest bash -c 'sleep 100000000'
-        ./run_in_container bash -c 'source DIRAC/tests/CI/run_docker_setup.sh && prepareEnvironment'
+        bash -c 'source run_in_container && source tests/CI/run_docker_setup.sh && prepareEnvironment'
     - name: Install server
-      run: ./run_in_container bash -c 'source DIRAC/tests/CI/run_docker_setup.sh && installServer'
+      run: bash -c 'source run_in_container && source tests/CI/run_docker_setup.sh && installServer'
     - name: Install client
-      run: ./run_in_container bash -c 'source DIRAC/tests/CI/run_docker_setup.sh && installClient'
+      run: bash -c 'source run_in_container && source tests/CI/run_docker_setup.sh && installClient'
     - name: Server tests
-      run: ./run_in_container bash -c 'source DIRAC/tests/CI/run_docker_setup.sh && testServer'
+      run: bash -c 'source run_in_container && source tests/CI/run_docker_setup.sh && testServer'
     - name: Client tests
-      run: ./run_in_container bash -c 'source DIRAC/tests/CI/run_docker_setup.sh && testClient'
+      run: bash -c 'source run_in_container && source tests/CI/run_docker_setup.sh && testClient'
     - name: Elasticsearch logs
-      run: ./run_in_container bash -c 'source DIRAC/tests/CI/run_docker_setup.sh && docker logs elasticsearch'
+      run: bash -c 'source run_in_container && source tests/CI/run_docker_setup.sh && docker logs elasticsearch'
     - name: Check test status
-      run: ./run_in_container bash -c 'source DIRAC/tests/CI/run_docker_setup.sh && checkErrors'
+      run: bash -c 'source run_in_container && source tests/CI/run_docker_setup.sh && checkErrors'
